### ISSUE TITLE
Nokogiri in config.rb

### ISSUE THREAD

**Issue by revans** [revans/Ti#7]
The nokogiri stuff needs to be pulled out of the generated application and that should be core to Ti itself.

**Comment by revans** [comment]
Referring to:

config  = File.open('tiapp.xml')
doc     = Nokogiri::XML(config)
config.close

**Comment by rupakg** [comment]
Correct. I will refactor the rakefile and remove the nokogiri dependency.

**Comment by baldrailers** [comment]
The parsing of tiapp.xml should be done after the project is generated. Or completely remove this since we capture these information:

  # Application
  APP_ID              = doc.xpath('ti:app/id').text
  APP_NAME            = doc.xpath('ti:app/name').text
  APP_DEVICE          = "iphone" 

When you create a new project

`ti new <name> <id> <platform>`
