### ISSUE TITLE
Weed through runtime dependencies

### ISSUE THREAD

**Issue by revans** [revans/Ti#9]
Need to figure out which runtime dependencies are actually needed.

**Comment by rupakg** [comment]
Here is the list and I don't think we need the ones marked with X:

sass - X
guard-sass - X
guard - X
guard-coffeescript - X
guard-livereload - X
jasmine - X
coffee-script - ? I see that you have a ti compile command that compiles coffeescripts, but do we really need that as a command or should it be handled via a Rake task? Unless you want to generate a Ti app that spits out JS instead of Coffeescript. Let me know.     

But, the above dependencies are required by the generated app., so it might be a good idea to create a Gemfile with these dependencies in the generated app. 

The only ones we need are:

colored
rake
nokogiri
erubis

Let me know what you think? I have tested it locally and it seems to work. I can take care of cleaning it up.

**Comment by revans** [comment]
Jasmine, Sass and CoffeeScript need to stay for now. 

The guard stuff can go. 

When a new project is generated, it creates a Coffeefile which the developer can specify which CoffeeScripts are to be compiled first. It also supports globbing. The Ti::Compiler::CoffeeScripts reads that file and compiles the coffeescript to javascript based on the order within the file. 

The Rakefile is going to be changed to use this new command.

**Comment by baldrailers** [comment]
The Rakefile will definitely go away since we are trying to almost every compilation script directly to binary. I think the main reason why `Rakefile` is still there is to be able to compile and build the project.

**Comment by rupakg** [comment]
I will leave Jasmine, Sass and CoffeeScript for now. I have commented on the Rakefile discussion in #10

**Comment by revans** [comment]
done
